databases:
  - name: yarukikkake_test_db
    databaseName: yarukikkake_test_db
    user: yarukikkake
    region: singapore
    plan: free

services:
  - type: web
    name: yarukikkake_test
    env: python
    region: singapore
    plan: free
    branch: deploy
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn iwaki_autumn.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yarukikkake_test_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true