# Generated by Django 3.2 on 2022-12-16 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yarukikkake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='ユーザーID')),
                ('display_name', models.CharField(max_length=255, verbose_name='表示名')),
            ],
        ),
        migrations.CreateModel(
            name='LineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(verbose_name='科目名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('push', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yarukikkake.lineuser', verbose_name='LINEユーザー')),
            ],
        ),
    ]
