# Generated by Django 3.2 on 2022-12-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarukikkake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='day_of_week',
            field=models.CharField(default='', max_length=20, verbose_name='曜日'),
        ),
    ]
