# Generated by Django 3.2 on 2022-12-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yarukikkake', '0002_subject_day_of_week'),
        ('yarukikkake', '0003_rename_linemessage_usersubject'),
    ]

    operations = [
    ]
