# Generated by Django 3.2 on 2022-12-20 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yarukikkake', '0004_merge_20221216_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineuser',
            name='state',
            field=models.IntegerField(default=1, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='usersubject',
            name='push',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yarukikkake.lineuser', verbose_name='LINEユーザー'),
        ),
        migrations.AlterField(
            model_name='usersubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yarukikkake.subject', verbose_name='対応科目'),
        ),
    ]
