# Generated by Django 3.2 on 2022-12-28 04:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('yarukikkake', '0005_auto_20221220_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='day_of_week',
            field=models.CharField(default='', max_length=100, verbose_name='曜日'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='タスクID')),
                ('task_name', models.CharField(max_length=30, verbose_name='タスク名')),
                ('task_start_time', models.DateTimeField(verbose_name='タスク開始時刻')),
                ('task_status', models.IntegerField(default=1, verbose_name='状態')),
                ('task_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yarukikkake.lineuser', verbose_name='LINEユーザー')),
            ],
        ),
    ]
