# Generated by Django 3.2 on 2022-12-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarukikkake', '0007_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_start_time',
            field=models.DateTimeField(null=True, verbose_name='タスク開始時刻'),
        ),
    ]
