# Generated by Django 3.2 on 2023-01-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yarukikkake', '0009_lineuser_latast_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100, unique=True, verbose_name='グループID')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yarukikkake.linegroup', verbose_name='LINEグループ'),
        ),
    ]
