# Generated by Django 3.2 on 2023-01-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarukikkake', '0010_auto_20230106_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineuser',
            name='day_broadcast',
            field=models.DateTimeField(blank=True, null=True, verbose_name='公式ライン上で未開始ユーザー確認された日付'),
        ),
    ]
